import { PDFDocument } from 'pdf-lib';

export type ForensicFlag = {
  sev: 'info' | 'warning' | 'critical';
  code: string;
  title: string;
  desc: string;
  pts: number;
};

export type PdfForensics = {
  metadata: {
    creationDate: string | null;
    modificationDate: string | null;
    producer: string | null;
    creator: string | null;
    author: string | null;
    title: string | null;
    subject: string | null;
    keywords: string | null;
    pdfVersion: string | null;
    pageCount: number;
    fileSizeBytes: number;
  };
  flags: ForensicFlag[];
  score: number; // 0-100, higher = more likely tampered
  verdict: 'clean' | 'suspicious' | 'likely_tampered';
};

// Free online PDF editors commonly used by freight scammers to alter documents.
// Seeing any of these in the Producer field is a strong red flag.
const SUSPICIOUS_EDITORS = [
  'ilovepdf',
  'smallpdf',
  'pdf24',
  'sejda',
  'pdfescape',
  'dochub',
  'pdffiller',
  'foxit online',
  'pdf filler',
  'lumin pdf',
  'deftpdf',
  'hipdf',
  'nitro online',
  'pdf candy',
  'soda pdf online',
];

// Signals that the PDF was generated by a real TMS or office software — used to
// REDUCE the score when everything else looks clean.
const LEGITIMATE_PRODUCERS = [
  'microsoft word',
  'microsoft office',
  'microsoft® word',
  'microsoft® office',
  'adobe acrobat',
  'adobe indesign',
  'adobe illustrator',
  'quickbooks',
  'latex',
  'wkhtmltopdf',
  'prince',
  'weasyprint',
  'chromium', // print-to-PDF from Chrome
  'mac os',   // macOS Quartz PDF export
  'quartz',
  // Common trucking TMS software:
  'mcleod',
  'tmw',
  'truckbase',
  'rose rocket',
  'tai software',
  'prophesy',
  'axon',
  'transflo',
  'truckingoffice',
  'dispatchware',
];

function toIso(d: Date | undefined): string | null {
  if (!d) return null;
  if (isNaN(d.getTime())) return null;
  return d.toISOString();
}

function getText(pdfDoc: PDFDocument, getter: () => string | undefined): string | null {
  try {
    const v = getter();
    if (v == null) return null;
    const s = String(v).trim();
    return s || null;
  } catch {
    return null;
  }
}

export async function analyzePdfForensics(buffer: Buffer): Promise<PdfForensics> {
  const pdfDoc = await PDFDocument.load(buffer, {
    updateMetadata: false,
    ignoreEncryption: true,
  });

  const creationDate = pdfDoc.getCreationDate();
  const modificationDate = pdfDoc.getModificationDate();
  const producerRaw = getText(pdfDoc, () => pdfDoc.getProducer());
  const creatorRaw = getText(pdfDoc, () => pdfDoc.getCreator());
  const author = getText(pdfDoc, () => pdfDoc.getAuthor());
  const title = getText(pdfDoc, () => pdfDoc.getTitle());
  const subject = getText(pdfDoc, () => pdfDoc.getSubject());
  const keywords = getText(pdfDoc, () => pdfDoc.getKeywords());

  // PDF version — pdf-lib exposes this only via low-level access.
  let pdfVersion: string | null = null;
  try {
    const header = buffer.subarray(0, 12).toString('utf8');
    const m = header.match(/%PDF-(\d\.\d)/);
    if (m) pdfVersion = m[1];
  } catch { /* ignore */ }

  const flags: ForensicFlag[] = [];

  // 1. Edited after creation (timestamp delta)
  if (creationDate && modificationDate) {
    const diffMs = modificationDate.getTime() - creationDate.getTime();
    const diffDays = diffMs / (1000 * 60 * 60 * 24);
    if (diffDays > 30) {
      flags.push({
        sev: 'critical',
        code: 'EDITED_LONG_AFTER_CREATION',
        title: `PDF edited ${Math.floor(diffDays)} days after creation`,
        desc: 'Brokers rarely edit rate confirmations weeks after generating them. Large edit-vs-creation gaps strongly suggest tampering.',
        pts: 35,
      });
    } else if (diffDays > 1) {
      flags.push({
        sev: 'warning',
        code: 'EDITED_AFTER_CREATION',
        title: `PDF edited ${Math.floor(diffDays)} day${Math.floor(diffDays) === 1 ? '' : 's'} after creation`,
        desc: 'Document was modified after its initial save. Could be a legitimate correction or post-hoc alteration.',
        pts: 15,
      });
    } else if (diffMs > 60_000) {
      const minutes = Math.floor(diffMs / 60_000);
      flags.push({
        sev: 'info',
        code: 'MINOR_EDITS',
        title: `Minor edits ${minutes} minute${minutes === 1 ? '' : 's'} after creation`,
        desc: 'Small same-session edits — usually innocent but worth noting.',
        pts: 3,
      });
    }
  }

  // 2. Suspicious online PDF editor detected
  if (producerRaw) {
    const producerLower = producerRaw.toLowerCase();
    const hit = SUSPICIOUS_EDITORS.find((e) => producerLower.includes(e));
    if (hit) {
      flags.push({
        sev: 'critical',
        code: 'SUSPICIOUS_EDITOR',
        title: `Processed with "${producerRaw}"`,
        desc: 'Free online PDF editor — commonly used by scammers to alter legitimate rate confirmations. Real brokers generate PDFs from their TMS or office software.',
        pts: 40,
      });
    }
  }

  // 3. Creator/Producer mismatch (download + edit pattern)
  if (producerRaw && creatorRaw) {
    const producerLower = producerRaw.toLowerCase();
    const creatorLower = creatorRaw.toLowerCase();
    const producerIsAcrobat = producerLower.includes('acrobat') || producerLower.includes('adobe');
    const creatorIsWord = creatorLower.includes('word') || creatorLower.includes('office');
    if (producerIsAcrobat && creatorIsWord && producerLower !== creatorLower) {
      flags.push({
        sev: 'warning',
        code: 'CREATOR_PRODUCER_MISMATCH',
        title: 'Document opened + re-saved by different software',
        desc: `Originally created in ${creatorRaw}, last saved by ${producerRaw}. Consistent with someone downloading a real rate con and editing it.`,
        pts: 15,
      });
    }
  }

  // 4. Metadata fully stripped
  if (!creationDate && !modificationDate && !producerRaw && !creatorRaw && !author) {
    flags.push({
      sev: 'warning',
      code: 'METADATA_STRIPPED',
      title: 'All PDF metadata has been removed',
      desc: 'Legitimate rate cons retain their creation/producer metadata. Scammers often strip it after tampering to hide their editing tool.',
      pts: 25,
    });
  }

  // 5. Author field looks like a person's name (not a company)
  if (author) {
    const trimmed = author.trim();
    const looksLikePerson =
      /^[A-Z][a-z]+\s+[A-Z][a-z]+$/i.test(trimmed) &&
      !/\b(llc|inc|co|corp|ltd|lp|logistics|freight|trucking|transport|brokerage)\b/i.test(trimmed);
    if (looksLikePerson) {
      flags.push({
        sev: 'info',
        code: 'PERSONAL_AUTHOR_NAME',
        title: `Author: "${trimmed}"`,
        desc: 'Document author is a person\'s name. Cross-check against the broker\'s known staff — a name that doesn\'t match their contact person is suspicious.',
        pts: 10,
      });
    }
  }

  // 6. Ancient PDF version
  if (pdfVersion) {
    const n = parseFloat(pdfVersion);
    if (n > 0 && n < 1.4) {
      flags.push({
        sev: 'info',
        code: 'OLD_PDF_VERSION',
        title: `PDF version ${pdfVersion}`,
        desc: `Very old PDF format. Modern TMS software generates v1.6+. Could indicate generation by outdated tooling.`,
        pts: 5,
      });
    }
  }

  // 7. Reward — recognized legitimate producer brings score down a notch
  let legitimateProducer = false;
  if (producerRaw) {
    const producerLower = producerRaw.toLowerCase();
    legitimateProducer = LEGITIMATE_PRODUCERS.some((p) => producerLower.includes(p));
  }

  const rawScore = flags.reduce((s, f) => s + f.pts, 0);
  const adjusted = legitimateProducer ? Math.max(0, rawScore - 5) : rawScore;
  const score = Math.min(100, adjusted);

  const verdict: PdfForensics['verdict'] =
    score >= 50 ? 'likely_tampered' : score >= 20 ? 'suspicious' : 'clean';

  return {
    metadata: {
      creationDate: toIso(creationDate),
      modificationDate: toIso(modificationDate),
      producer: producerRaw,
      creator: creatorRaw,
      author,
      title,
      subject,
      keywords,
      pdfVersion,
      pageCount: pdfDoc.getPageCount(),
      fileSizeBytes: buffer.length,
    },
    flags,
    score,
    verdict,
  };
}
